### ISSUE TITLE
Build failure on musl

### ISSUE THREAD

**Issue by anarchpenguin** [padenot/audio_thread_priority#3]
12:16.01 error[E0063]: missing fields `sched_ss_init_budget`, `sched_ss_low_priority`, `sched_ss_max_repl` and 1 other field in initializer of `libc::sched_param`
12:16.01   --> /var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/third_party/rust/audio_thread_priority/src/rt_linux.rs:97:21
12:16.01    |
12:16.01 97 |     let mut param = libc::sched_param { sched_priority: 0 };
12:16.01    |                     ^^^^^^^^^^^^^^^^^ missing `sched_ss_init_budget`, `sched_ss_low_priority`, `sched_ss_max_repl` and 1 other field
12:16.03 error: aborting due to previous error
12:16.03 For more information about this error, try `rustc --explain E0063`.
12:16.05 error: Could not compile `audio_thread_priority`.
12:16.05 Caused by:
12:16.05   process didn't exit successfully: `CARGO_PKG_VERSION_PRE= CARGO=/usr/bin/cargo-1.36.0 CARGO_PKG_AUTHORS='Paul Adenot <paul@paul.cx>' CARGO_PKG_HOMEPAGE= CARGO_PKG_NAME=audio_thread_priority LD_LIBRARY_PATH='/var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/ff/release/deps:/usr/lib' CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_REPOSITORY='https://github.com/padenot/audio_thread_priority' CARGO_PKG_VERSION_MINOR=15 CARGO_MANIFEST_DIR=/var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/third_party/rust/audio_thread_priority CARGO_PKG_VERSION=0.15.0 CARGO_PKG_DESCRIPTION='Bump a thread to real-time priority, for audio work, on Linux, Windows and macOS' /usr/bin/rustc --crate-name audio_thread_priority /var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/third_party/rust/audio_thread_priority/src/lib.rs --color always --crate-type staticlib --crate-type rlib --emit=dep-info,link -C opt-level=2 -C panic=abort -C codegen-units=1 -C metadata=4b9f349ffbc3e8bb -C extra-filename=-4b9f349ffbc3e8bb --out-dir /var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/ff/x86_64-gentoo-linux-musl/release/deps --target x86_64-gentoo-linux-musl -C linker=/var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/build/cargo-linker -L dependency=/var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/ff/x86_64-gentoo-linux-musl/release/deps -L dependency=/var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/ff/release/deps --extern cfg_if=/var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/ff/x86_64-gentoo-linux-musl/release/deps/libcfg_if-095ac5a2575e7686.rlib --extern dbus=/var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/ff/x86_64-gentoo-linux-musl/release/deps/libdbus-9de631a4f46d820b.rlib --extern libc=/var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/ff/x86_64-gentoo-linux-musl/release/deps/liblibc-609acc94656de7ae.rlib --extern log=/var/tmp/portage/www-client/firefox-69.0_beta12/work/firefox-69.0/ff/x86_64-gentoo-linux-musl/release/deps/liblog-7f753235fd5d8bd1.rlib --cap-lints warn -C opt-level=2 --cap-lints warn -L native=/usr/lib` (exit code: 1)

**Comment by anarchpenguin** [comment]
http://rust-lang.github.io/libc/x86_64-unknown-linux-musl/libc/struct.sched_param.html

For reference how sched_param is implemented for musl

**Comment by padenot** [comment]
Sorry I was on vacations.

Since we don't care about the value there and then query the data, it's best to have this initialized to zero than to special-case musl.

Fixed in a1443a02667c649cb72873a45b98fffbd2eac5a8. I've released version 0.18.0, that I will import in Firefox now, so your build should be fixed shortly.
