### ISSUE TITLE
cann't be formattered with the default formatter

### ISSUE THREAD

**Issue by anarchpenguin** [padenot/audio_thread_priority#4]
91:57.14 error[E0277]: `*mut libc::c_void` doesn't implement `std::fmt::Display`
91:57.14    --> /var/tmp/portage/www-client/firefox-70.0_beta3/work/firefox-70.0/third_party/rust/audio_thread_priority/src/rt_linux.rs:103:50
91:57.14     |
91:57.14 103 |         error!("pthread_getschedparam error {}", pthread_id);
91:57.14     |                                                  ^^^^^^^^^^ `*mut libc::c_void` cannot be formatted with the default formatter
91:57.15     |
91:57.15     = help: the trait `std::fmt::Display` is not implemented for `*mut libc::c_void`
91:57.15     = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
91:57.15     = note: required by `std::fmt::Display::fmt`
91:57.15 error[E0277]: `*mut libc::c_void` doesn't implement `std::fmt::Display`
91:57.15    --> /var/tmp/portage/www-client/firefox-70.0_beta3/work/firefox-70.0/third_party/rust/audio_thread_priority/src/rt_linux.rs:130:45
91:57.15     |
91:57.16 130 |         warn!("could not demote thread {}", rt_priority_handle.pthread_id);
91:57.16     |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `*mut libc::c_void` cannot be formatted with the default formatter
91:57.16     |
91:57.16     = help: the trait `std::fmt::Display` is not implemented for `*mut libc::c_void`
91:57.17     = note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
91:57.17     = note: required by `std::fmt::Display::fmt`
91:57.17 error: aborting due to 2 previous errors

**Comment by anarchpenguin** [comment]
This is in 70_beta3

**Comment by anarchpenguin** [comment]
I guess I am just gonna patch out the offending code so I can begin testing. Please let me know if you need me to retest something for you.

**Comment by padenot** [comment]
Yes, sorry, I'll get to this today.

**Comment by padenot** [comment]
Fixed by f6fecc01e7d44220678796ab9f86e51bed1afd06.

Additionally, I've added musl as a target in Travis, to prevent this from happening in the future.

**Comment by anarchpenguin** [comment]
Thanks for the fix, I went ahead and brought the current beta to head and tested. 
https://dev.gentoo.org/~anarchy/patches/6009_musl_audio_thread_priority.patch

Feel free to update the info for you and push it to upstream if you would like.
