### ISSUE TITLE
0.22 release?

### ISSUE THREAD

**Issue by kinetiknz** [padenot/audio_thread_priority#9]
It'd be great to do a 0.22 release including 5c7c4842a540b8b54a9bbb565384b44b682db348 to fix builds on unsupported platforms and resolve [BMO 1611648](https://bugzilla.mozilla.org/show_bug.cgi?id=1611648), which currently manifest as build failures in Gecko Android builds.

**Comment by padenot** [comment]
Fixed by 696aab00d7bd88fe8811634f8fe97d832a7d6f4b. I'm now doing a patch to bump this in Gecko, thanks for the heads up.

**Comment by kinetiknz** [comment]
Thanks! I've bumped the version in https://github.com/djg/audioipc-2 now.
